name: "Docker Build CI"

on:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        id: qemu
        with:
          platforms: amd64,arm64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: moonrailgun/tianji
          tags: |
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          # context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
